# Copyright 2023 Paul Guyot <pguyot@kallisys.net>
# SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later

name: "Build"

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: erlang:28
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run fmt task
        run: |
          rebar3 as check fmt --check
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ["21", "22", "23", "24", "25", "26", "27", "28"]
    container: erlang:${{ matrix.otp }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: |
          rebar3 compile
      - name: Escriptize
        run: |
          rebar3 escriptize
      - name: Generate avm package
        run: |
          rebar3 atomvm packbeam
      - name: Generate uf2
        run: |
          rebar3 atomvm uf2create
      - name: Ensure tests run properly
        run: |
          _build/default/bin/benchmark
      - name: Upload AVM package
        uses: actions/upload-artifact@v4
        with:
          name: avm-compiled-with-otp-${{ matrix.otp }}
          path: _build/default/lib/benchmark.avm
      - name: Upload UF2 image
        uses: actions/upload-artifact@v4
        with:
          name: uf2-compiled-with-otp-${{ matrix.otp }}
          path: _build/default/lib/benchmark.uf2
      - name: Upload escript
        uses: actions/upload-artifact@v4
        with:
          name: escript-compiled-with-otp-${{ matrix.otp }}
          path: _build/default/bin/benchmark
